# .air.toml
root = "."
tmp_dir = "tmp"
[build]
  cmd = "go build -o ./tmp/main ."
  bin = "tmp/main"
  poll = true
[log]
  time = true
[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
[watch]
  include = ["*.go"]
  exclude = []
  poll = true
  delay = 500
